package com.ntnn.database;

import com.ntnn.stdf.StdfRecord;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;

public class DatabaseClient implements AutoCloseable {
    private final HikariDataSource dataSource;

    public DatabaseClient(String jdbcUrl, String username, String password) {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl(jdbcUrl);
        config.setUsername(username);
        config.setPassword(password);
        config.setMaximumPoolSize(20); // Scale concurrent writes with Virtual Threads
        config.setMinimumIdle(5);
        config.setConnectionTimeout(30000); // 30 seconds
        
        // Oracle performance optimizations
        config.addDataSourceProperty("implicitCachingEnabled", "true");
        config.addDataSourceProperty("metadataPoolable", "true");

        this.dataSource = new HikariDataSource(config);
    }

    public void initializeSchema() throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            
            // Create STDF_LOTS table
            try {
                stmt.execute("""
                    CREATE TABLE STDF_LOTS (
                        LOT_ID VARCHAR2(100) PRIMARY KEY,
                        PART_TYP VARCHAR2(100),
                        JOB_NAM VARCHAR2(100),
                        OPER_NAM VARCHAR2(100),
                        START_TIME TIMESTAMP,
                        SETUP_TIME TIMESTAMP
                    )
                """);
            } catch (SQLException e) {
                if (e.getErrorCode() != 955) { // ORA-00955: name is already used by an existing object
                    throw e;
                }
            }

            // Create TEST_RESULTS table
            try {
                stmt.execute("""
                    CREATE TABLE TEST_RESULTS (
                        TEST_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        LOT_ID VARCHAR2(100),
                        TEST_NUM NUMBER(19),
                        HEAD_NUM NUMBER(3),
                        SITE_NUM NUMBER(3),
                        RESULT NUMBER,
                        TEST_TXT VARCHAR2(255),
                        LO_LIMIT NUMBER,
                        HI_LIMIT NUMBER,
                        TEST_FLAG NUMBER(3)
                    )
                """);
            } catch (SQLException e) {
                if (e.getErrorCode() != 955) {
                    throw e;
                }
            }
        }
    }

    public void insertLot(StdfRecord.MirRecord mir) throws SQLException {
        String sql = """
            MERGE INTO STDF_LOTS t
            USING (SELECT ? AS LOT_ID, ? AS PART_TYP, ? AS JOB_NAM, ? AS OPER_NAM, ? AS START_TIME, ? AS SETUP_TIME FROM dual) s
            ON (t.LOT_ID = s.LOT_ID)
            WHEN MATCHED THEN
                UPDATE SET t.PART_TYP = s.PART_TYP, t.JOB_NAM = s.JOB_NAM, t.OPER_NAM = s.OPER_NAM, t.START_TIME = s.START_TIME, t.SETUP_TIME = s.SETUP_TIME
            WHEN NOT MATCHED THEN
                INSERT (LOT_ID, PART_TYP, JOB_NAM, OPER_NAM, START_TIME, SETUP_TIME)
                VALUES (s.LOT_ID, s.PART_TYP, s.JOB_NAM, s.OPER_NAM, s.START_TIME, s.SETUP_TIME)
        """;
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, mir.lotId());
            ps.setString(2, mir.partType());
            ps.setString(3, mir.jobName());
            ps.setString(4, mir.operatorName());
            ps.setTimestamp(5, Timestamp.from(Instant.ofEpochSecond(mir.startTime())));
            ps.setTimestamp(6, Timestamp.from(Instant.ofEpochSecond(mir.setupTime())));
            ps.executeUpdate();
        }
    }

    public void insertTestResult(String lotId, StdfRecord.PtrRecord ptr) throws SQLException {
        String sql = """
            INSERT INTO TEST_RESULTS (LOT_ID, TEST_NUM, HEAD_NUM, SITE_NUM, RESULT, TEST_TXT, LO_LIMIT, HI_LIMIT, TEST_FLAG)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """;
        try (Connection conn = dataSource.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, lotId);
            ps.setLong(2, ptr.testNum());
            ps.setInt(3, ptr.headNum());
            ps.setInt(4, ptr.siteNum());
            ps.setDouble(5, ptr.result());
            ps.setString(6, ptr.testTxt());
            ps.setDouble(7, ptr.loLimit());
            ps.setDouble(8, ptr.hiLimit());
            ps.setInt(9, ptr.testFlag());
            ps.executeUpdate();
        }
    }

    public HikariDataSource getDataSource() {
        return dataSource;
    }

    @Override
    public void close() {
        if (dataSource != null) {
            dataSource.close();
        }
    }
}
